server:
  port: 8083
  servlet:
    context-path: /flash-sale-demo
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    name: production
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #--------------------------
    # ����Ϊ���ӳصĲ������ã�Ӧ�õ�������������Դ��
    # ��ʼ����С����С�����
    initialSize: 5
    minIdle: 1
    maxActive: 50
    # ���û�ȡ���ӵȴ���ʱ��ʱ��
    maxWait: 60000
    # ���ü����òŽ���һ�μ�⣬�����Ҫ�رյĿ������ӣ���λ�Ǻ���
    timeBetweenEvictionRunsMillis: 60000
    # ����һ�������ڳ�����С�����ʱ�䣬��λ�Ǻ���
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # ��PSCache������ָ��ÿ��������PSCache�Ĵ�С
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
    # ���ü��ͳ�����ص�filters��ȥ�����ؽ���sql�޷�ͳ�ƣ�'wall'���ڷ���ǽ
    filters: stat,wall,log4j
    # ͨ��connectProperties��������mergeSql���ܣ���SQL��¼
    connectionProperties:
      druid.stat.mergeSql: true
      druid.stat.slowSqlMillis: 5000
    # �ϲ����DruidDataSource�ļ������
    #spring.datasource.useGlobalDataSourceStat=true




mybatis-plus:
  # ����Ƿ���src/main/javaĿ¼�� classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # ����Ƿ���resourceĿ¼ classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  #ʵ��ɨ�裬���package�ö��Ż��߷ֺŷָ�
  typeAliasesPackage: com.giovanny.flashsaledemo.entity.po
  global-config:
    #�ֶβ��� 0:"�����ж�",1:"�� NULL �ж�"),2:"�ǿ��ж�"
    #field-strategy: 1
    #�շ��»���ת��
    #db-column-underline: true
    #ˢ��mapper ��������
    #refresh-mapper: true
    #���ݿ��д�»���ת��
    #capital-mode: true
    # Sequence���нӿ�ʵ��������
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #�߼�ɾ�����ã�����3�����ã�
    #logic-delete-value: 1
    #logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #�Զ��������Խӿ�ʵ��
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    db-config:
      #��������  0:"���ݿ�ID����", 1:"�û�����ID",2:"ȫ��ΨһID (��������ΨһID)", 3:"ȫ��ΨһID UUID";
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #����JdbcTypeForNull
    #jdbc-type-for-null: 'null'

executor:
  corePoolSize: 100
  maximumPoolSize: 120
  keepAliveTime: 5
  queueSize: 150

log:
  path: /log
  level: info
  project-name: flash-sale-demo